### ISSUE TITLE
InfluxDB config [question]

### ISSUE THREAD

**Issue by blazmag** [mlabouardy/grafana-dashboards#1]
Great work on the dashboard! 

I know this is out of scope, but any chance you could share the steps on how to configure InfluxDB to work with gitlab & grafana - how to use your influxdb.conf?

**Comment by mlabouardy** [comment]
@blazmag here you go : [GitLab Performance Monitoring with Grafana](http://www.blog.labouardy.com/gitlab-performance-monitoring-with-grafana/)

**Comment by blazmag** [comment]
@mlabouardy 👍  thanks! Best to link the blog in the repo readme.md for backlink and visibility :)
