### ISSUE TITLE
MySQL dashboard has a couple hardcoded servers in the queries

### ISSUE THREAD

**Issue by joelsdc** [mlabouardy/grafana-dashboards#2]
Hi, 

Nice job with this dashboard! I had to do some changes to make it work with my setup but it looks awesome... Just wanted to let you know you have hardcoded the `10.100.248.44:3306` server in a couple queries. 

Offtopic, have you found a way for Telegraf pulling metrics from MySQL not messing up the graphs?

For example, I have to new servers installed that are not in production yet, just basic OS installacion + MySQL. I gather metrics every 10s, so with 0 prod traffic this is my current graph:

![image](https://user-images.githubusercontent.com/16212586/35737856-cf8950ec-07e1-11e8-8d08-ae31aa38b813.png)

Any suggestion in how to handle those spikes every time Telegraf pulls data from MySQL?

Thanks!
Joel.

**Comment by mlabouardy** [comment]
thanks ! fixed :)
By default telegraf will gather all metrics, events & statistics, you can reduce number of requests by using the  _interval_slow_ attribute - check https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql
